[project]
name = "mlops-118"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "boto3>=1.43.105",
    "fastapi>=0.142.1",
    "mlflow>=3.16.1",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "skops>=0.16.0",
    "uvicorn>=0.54.0",
]
